import React, { useState, useEffect } from "react";
import "./Dashboard.css";

const TIME_RANGES = ["today", "7d", "30d", "all"];

const rangeLabel = {
  today: "Today",
  "7d": "Last 7 days",
  "30d": "Last 30 days",
  all: "All time",
};

// KPI metrics per range
const taskMetricsByRange = {
  today: { total: 32, inProgress: 12, completed: 15, overdue: 5 },
  "7d": { total: 48, inProgress: 18, completed: 24, overdue: 6 },
  "30d": { total: 120, inProgress: 30, completed: 80, overdue: 10 },
  all: { total: 260, inProgress: 40, completed: 200, overdue: 20 },
};

// Analytics per range
const analyticsByRange = {
  today: { completion: 47, utilization: 0.68, throughput: 0.82, efficiency: 0.74 },
  "7d": { completion: 53, utilization: 0.72, throughput: 0.85, efficiency: 0.78 },
  "30d": { completion: 61, utilization: 0.75, throughput: 0.88, efficiency: 0.8 },
  all: { completion: 70, utilization: 0.8, throughput: 0.9, efficiency: 0.84 },
};

// SVG line paths per range (simple smooth curves)
const linePathsByRange = {
  today: "M5 70 C 40 60, 80 80, 120 65 S 220 55, 295 65",
  "7d": "M5 72 C 40 50, 80 75, 130 55 S 220 40, 295 70",
  "30d": "M5 68 C 60 40, 110 80, 160 50 S 240 30, 295 65",
  all: "M5 75 C 70 35, 130 75, 190 45 S 250 35, 295 60",
};

// Agent sets per range (progress changes to show movement)
const agentsByRange = {
  today: [
    { id: 1, name: "Agent A", status: "Active", task: "Refactoring module X", progress: 72 },
    { id: 2, name: "Agent B", status: "Idle", task: "—", progress: 0 },
    { id: 3, name: "Agent C", status: "Running", task: "Generating API docs", progress: 45 },
  ],
  "7d": [
    { id: 1, name: "Agent A", status: "Active", task: "Refactoring module X", progress: 85 },
    { id: 2, name: "Agent B", status: "Running", task: "Implementing integration tests", progress: 40 },
    { id: 3, name: "Agent C", status: "Running", task: "Generating API docs", progress: 60 },
  ],
  "30d": [
    { id: 1, name: "Agent A", status: "Completed", task: "Module X refactor merged", progress: 100 },
    { id: 2, name: "Agent B", status: "Active", task: "Performance profiling", progress: 55 },
    { id: 3, name: "Agent C", status: "Running", task: "Writing integration docs", progress: 70 },
  ],
  all: [
    { id: 1, name: "Agent A", status: "Completed", task: "Multiple refactor cycles", progress: 100 },
    { id: 2, name: "Agent B", status: "Active", task: "Ongoing UI improvements", progress: 65 },
    { id: 3, name: "Agent C", status: "Running", task: "Maintaining API docs", progress: 80 },
  ],
};

// Base activity feeds per range
const baseFeedByRange = {
  today: [
    "New PR generated by Agent C",
    "Agent A completed a subtask",
    "Agent C updated API documentation",
    "Overdue task flagged for review",
  ],
  "7d": [
    "Agent B completed integration test suite",
    "New kanban card created: Dependency cleanup",
    "Agent A resolved 5 code review comments",
    "Agent C generated summary for sprint review",
  ],
  "30d": [
    "Agents completed migration to new build pipeline",
    "Agent A reduced bundle size by 12%",
    "Agent B automated smoke tests for staging",
    "Agent C produced onboarding docs for new developers",
  ],
  all: [
    "Initial agentic workflow prototype deployed",
    "Kanban board integrated with coding agents",
    "Live monitoring added for agent sessions",
    "Analytics dashboard introduced for AI workflows",
  ],
};

export default function Dashboard() {
  const [timeRange, setTimeRange] = useState("today");
  const [dynamicToday, setDynamicToday] = useState([]);

  // live updates only when "today" is selected
  useEffect(() => {
    if (timeRange !== "today") return;

    const interval = setInterval(() => {
      const candidates = [
        "Agent B assigned a new task: UI polish",
        "Agent A completed a refactor for module X",
        "New PR generated by Agent C",
        "New kanban card created: Agent handoff flow",
      ];
      const random = candidates[Math.floor(Math.random() * candidates.length)];

      setDynamicToday((prev) => {
        const next = [{ id: Date.now(), message: random }, ...prev];
        return next.slice(0, 6);
      });
    }, 6000);

    return () => clearInterval(interval);
  }, [timeRange]);

  const metrics = taskMetricsByRange[timeRange];
  const analytics = analyticsByRange[timeRange];
  const agents = agentsByRange[timeRange];
  const linePath = linePathsByRange[timeRange];

  const combinedFeed =
    timeRange === "today"
      ? [...dynamicToday.map((d) => d.message), ...baseFeedByRange.today]
      : baseFeedByRange[timeRange];

  return (
    <div className="dashboard-body">
      {/* PAGE HEADER */}
      <header className="dash-header-bar">
        <h1 className="page-title">Dashboard</h1>
        <div className="header-right">
          <input
            className="search-input"
            placeholder="Search tasks or agents..."
          />
          <div className="user-chip">PM</div>
        </div>
      </header>

      {/* TOP KPI ROW */}
      <div className="stats-row">
        <div className="stats-card">
          <h4>Total Tasks</h4>
          <p>{metrics.total}</p>
          <span className="stat-sub">All tasks in the system</span>
        </div>
        <div className="stats-card">
          <h4>In Progress</h4>
          <p>{metrics.inProgress}</p>
          <span className="stat-sub">Currently being handled</span>
        </div>
        <div className="stats-card">
          <h4>Completed</h4>
          <p>{metrics.completed}</p>
          <span className="stat-sub">Successfully finished</span>
        </div>
        <div className="stats-card">
          <h4>Overdue</h4>
          <p className="overdue">{metrics.overdue}</p>
          <span className="stat-sub">Require attention</span>
        </div>
      </div>

      {/* TIME RANGE FILTER */}
      <div className="time-filter-row">
        <span className="time-filter-label">Time range:</span>
        <div className="time-filter-pills">
          {TIME_RANGES.map((range) => (
            <button
              key={range}
              className={`time-pill ${
                timeRange === range ? "active" : ""
              }`}
              onClick={() => {
                setTimeRange(range);
                if (range !== "today") setDynamicToday([]);
              }}
              type="button"
            >
              {rangeLabel[range]}
            </button>
          ))}
        </div>
      </div>

      {/* MAIN GRID */}
      <div className="main-grid">
        {/* TOP ROW: PIE + LINE */}
        <div className="grid-top">
          {/* PIE + METRICS */}
          <section className="panel analytics-panel">
            <div className="panel-header">
              <h2>Workflow Analytics</h2>
              <span className="panel-tag subtle">Last 7 days</span>
            </div>

            <div className="analytics-top">
              <div
                className="analytics-donut"
                style={{
                  "--donut-stop": `${analytics.completion}%`,
                }}
              >
                <div className="donut-inner">
                  <p>{analytics.completion}%</p>
                  <span>Overall progress</span>
                </div>
              </div>

              <div className="metrics-bars">
                <div className="metric-row">
                  <span>Agent Utilization</span>
                  <div className="metric-bar">
                    <div
                      className="metric-bar-fill"
                      style={{ width: `${analytics.utilization * 100}%` }}
                    />
                  </div>
                </div>

                <div className="metric-row">
                  <span>Task Throughput</span>
                  <div className="metric-bar">
                    <div
                      className="metric-bar-fill"
                      style={{ width: `${analytics.throughput * 100}%` }}
                    />
                  </div>
                </div>

                <div className="metric-row">
                  <span>AI Efficiency Score</span>
                  <div className="metric-bar">
                    <div
                      className="metric-bar-fill"
                      style={{ width: `${analytics.efficiency * 100}%` }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* LINE CHART */}
          <section className="panel linechart-panel">
            <div className="panel-header">
              <h2>Workflow Efficiency</h2>
              <span className="panel-tag subtle">{rangeLabel[timeRange]}</span>
            </div>

            {/* REAL LINE CHART */}
<div className="line-chart">
  <div className="line-chart-header">
    <span>Tasks completed over time</span>
    <span className="chart-period">Weekly trend</span>
  </div>

  <svg className="linechart-svg" viewBox="0 0 500 160" preserveAspectRatio="none">
    {/* Polyline (animated) */}
    <polyline
      className="chart-line"
      points="0,120 60,100 120,105 180,80 240,60 300,70 360,50 420,65 480,40"
      fill="none"
      stroke="#4f46e5"
      strokeWidth="3"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
</div>

          </section>
        </div>

        {/* BOTTOM ROW: FEED + AGENTS */}
        <div className="grid-bottom">
          {/* LIVE FEED */}
          <section className="panel feed-panel">
            <div className="panel-header">
              <h2>Live Activity Feed</h2>
              <span className="panel-tag subtle">
                {timeRange === "today" ? "Real-time" : "Historical"}
              </span>
            </div>

            <ul className="feed-list">
              {combinedFeed.map((item, index) => (
                <li key={`${item}-${index}`} className="feed-item">
                  <span className="plane-icon" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          {/* AGENT STATUS */}
          <section className="panel agent-panel">
            <div className="panel-header">
              <h2>Agent Status</h2>
              <span className="panel-tag">Live</span>
            </div>

            {agents.map((agent) => (
              <div key={agent.id} className="agent-card">
                <div className="agent-row">
                  <div>
                    <strong>{agent.name}</strong>
                    <p className="agent-task">Task: {agent.task}</p>
                  </div>
                  <span className={`agent-badge ${agent.status.toLowerCase()}`}>
                    {agent.status}
                  </span>
                </div>

                <div className="agent-progress">
                  <div
                    className="agent-progress-fill"
                    style={{ width: `${agent.progress}%` }}
                  />
                </div>
              </div>
            ))}
          </section>
        </div>
      </div>
    </div>
  );
}
